name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # Se ejecuta una vez al día
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "generated profile 3d"
          file_pattern: "profile-3d-contrib/*"          git push origin main
